# Generated by Django 5.1.5 on 2025-01-27 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='price_tracker.trackeditem'),
        ),
    ]
