# Generated by Django 5.1.5 on 2025-01-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0002_alter_pricehistory_options_alter_pricehistory_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackeditem',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
