# Generated by Django 5.1.5 on 2025-02-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0004_alter_trackeditem_lowest_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('current_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lowest_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pricehistory',
            options={},
        ),
        migrations.RenameField(
            model_name='trackeditem',
            old_name='last_checked',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='trackeditem',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='trackeditem',
            name='lowest_price',
        ),
        migrations.AddField(
            model_name='trackeditem',
            name='tracked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trackeditem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
