# Generated by Django 5.1.5 on 2025-02-04 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0005_itemresult_alter_pricehistory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackeditem',
            name='name',
        ),
    ]
