# Generated by Django 5.1.5 on 2025-02-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0007_remove_itemresult_lowest_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemresult',
            name='url',
            field=models.URLField(),
        ),
    ]
