# Generated by Django 5.1.5 on 2025-02-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0008_alter_itemresult_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemresult',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
